version: '3.3'

services:
    myredis:
        image: redis:latest
        container_name: myredis
        ports:
            - "6379:6379"
        restart: always
        privileged: true
        networks:
            - app-network
            
    mysql:
        image: mariadb:latest
        container_name: mysql
        ports:
            - "3306:3306"
        restart: always
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: MyDBRoot123
            MYSQL_DATABASE: php
            MYSQL_USER: php
            MYSQL_PASSWORD: php
        networks:
            - app-network

            
    myphp:
        depends_on:
            - myredis
            - mysql
        build: ./src/php
        container_name: myphp
        privileged: true
        volumes:
            - $HOME/cca2/src:/var/www/html
        ports:
            - "9000:9000"
        restart: always
        networks:
            - app-network

    mynginx:
        depends_on:
            - myphp
        image: nginx:latest
        container_name: mynginx
        ports:
            - "8080:80"
        restart: always
        privileged: true
        volumes:
            - $HOME/cca2/src:/var/www/html
            - $HOME/cca2/src/nginx.ini:/etc/nginx/conf.d/default.conf
            - $HOME/cca2/src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
            - $HOME/cca2/src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
        networks:
            - app-network



networks:
    app-network:
        driver: bridge


